### ISSUE TITLE
Parse objects from existing IDF file into BHoM

### ISSUE THREAD

**Issue by tg359** [BHoM/EnergyPlus_Toolkit#100]
#### Description:

Useful for:
- Loading predefined datasets into EnergyPlus_Toolkit
- Allowing full Push/Pull functionality from later Adapter developments (and diffing between existing objects and new ones to prevent duplicates when appending to existing file)
- Visualising output/files generated in other tools

Also requires bidirectional to/from BHoM methods for each EnergyPlusClass object ... quite an undertaking if we want to go fully into BHoM from EnergyPlus.

**Comment by BingWangUS** [comment]
Adding one vote to this functionality as @KentonPhillips-BH and I were having some discussion and trying to find a way to abstract design days from an idf file.

**Comment by tg359** [comment]
Closed as EnergyPlusToolkit phased out in favour of HB-Energy.
