### ISSUE TITLE
Namespace of several objects show they reside in Adapter when they should reside in oM

### ISSUE THREAD

**Issue by tg359** [BHoM/EnergyPlus_Toolkit#103]

**Comment by FraserGreenroyd** [comment]
Is this a result of the namespace changes from BH.oM.EnergyPlus to BH.oM.Adapters.EnergyPlus? If so, that's deliberate that @alelom assisted us with. Might be worth a quick discussion tomorrow? :smile:

**Comment by tg359** [comment]
Closed as EnergyPlusToolkit phased out in favour of HB-Energy.
