### ISSUE TITLE
Component error with use of Public Beta 3.3

### ISSUE THREAD

**Issue by linaeriksson** [BHoM/EnergyPlus_Toolkit#108]
#### Description:
The component GroundTemperatureMonthly is in a toolkit now accessible by the Public beta, and therefore the script can not run properly. 

#### Steps to reproduce:
Try opening the script with the Public beta 3.3

#### Expected behaviour:
Put that component in a toolkit accessible by the public beta.

**Comment by rboulton-BH** [comment]
Toolkit is no longer in the Beta release so I'm closing the issue
