### ISSUE TITLE
EnergyPlus_Toolkit: Name passing of the BuildingSurface: Detailed

### ISSUE THREAD

**Issue by AlaaAlfakara** [BHoM/EnergyPlus_Toolkit#23]
It seems that any BHoM object panel (surface) with name "0" gets overwritten to a random number by Open studio like that "{69352620-418a-4611-b7c8-e08f8465fd30}". 
Maybe we should avoid naming using "0".

**Comment by tg359** [comment]
Closed as E+Toolkit phased out in favour of alternative IDF handling methods.
