### ISSUE TITLE
EnergyPlus_Toolkit: Openstudio Shade export 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/EnergyPlus_Toolkit#3]
when we export shade from Openstudio
shade surface generate seperate Space this is not right and we need have this in mind
we should not have AdjacentSpaceId for shade

```
    <Surface id="Shade" surfaceType="Shade">
      <AdjacentSpaceId spaceIdRef="_b58c9229-7d70-4c44-abdb-06880a97c24c_"/>
      <RectangularGeometry>
        <Azimuth>90</Azimuth>
        <CartesianPoint>
          <Coordinate>4.00000
```

![image](https://user-images.githubusercontent.com/26113670/53573248-f08c3680-3b64-11e9-989a-e8d5bd0a91e0.png)
![image](https://user-images.githubusercontent.com/26113670/53573347-30ebb480-3b65-11e9-909d-baa8b612e9b4.png)

**Comment by tg359** [comment]
Closed as E+ Toolkit being phased out in favour of other means of handling IDF files.
