### ISSUE TITLE
Energy_Plus: Import error to OpenStudio 2.7.0

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/EnergyPlus_Toolkit#4]
there is import error on out calibration model:

`WorkspaceObject is not IddObjectType: Zone`

Test file:
[CalibrationModel_901.zip](https://github.com/BuroHappoldEngineering/EnergyPlus_Toolkit/files/2915400/CalibrationModel_901.zip)

**Comment by tg359** [comment]
Closed as E+ Toolkit being phased out in favour of other means of handling IDF files.
