### ISSUE TITLE
EnergyPlus_Toolkit: Repo tidy-up

### ISSUE THREAD

**Issue by tg359** [BHoM/EnergyPlus_Toolkit#44]
#### Broken rules:

Repo is very messy given it's beginnings as a hacked-together solution.

#### Suggestions to restore compliance:

A tidy up and slight refactoring to make it ready for further development.

**Comment by FraserGreenroyd** [comment]
This was handled when the code was split between this repo and open studio repo. Further issues to be raised for ongoing work and tidy up.
