### ISSUE TITLE
Convert from DDY file to generate SizingPeriod:DesignDay object

### ISSUE THREAD

**Issue by tg359** [BHoM/EnergyPlus_Toolkit#85]
#### Description:

See issue and [here's a couple of example DDY files that can be tested on](https://github.com/BHoM/EnergyPlus_Toolkit/files/4819970/example_ddy.zip).

**Comment by BingWangUS** [comment]
@KentonPhillips-BH found this related issue to our discussion today.

**Comment by tg359** [comment]
Closed as E+Toolkit phased out in favour of alternative energy handling methods (Ladybug).
